### ISSUE TITLE
🗞 Add Setup section to README.md file

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-frontend#1]
📄 Add Setup section to README.md file
---

To allow easy setup of the project, create a **Setup** section in the `README.md` file and add steps on how locally allow the setup of the project.

The _Setup_ Section must include the following -

* Create a Fork
* `git clone` the project
* Check for Prerequisites for the project
* Commands for Initiating and running the project

**Comment by Snehil0603** [comment]
I would like to work on it.
