### ISSUE TITLE
🖌 Improve Graphics

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-frontend#3]
🖌 Improve Graphics
---

The current graphics in the **Features** section of the website are low resolution and don't match the quality of the website. 
Find similar yet high-quality pictures and replace them in the project. 

**NOTE: Ensure the new images' format and aspect ratio don't break the responsiveness of the website.**

**Comment by rahul-jamwal** [comment]
Hello sir
I'd like to work on this
Can you please assign it to me?
