### ISSUE TITLE
⚡️Add Tools section to Navbar

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-frontend#4]
⚡️Add **_Tools_** section to Navbar
---

Add a **_Tools_** in the Navbar which scrolls down to _Tools at Disposal_ Section of the Website.

<img width="562" alt="Screenshot 2022-09-30 at 4 53 51 AM" src="https://user-images.githubusercontent.com/76054330/193159157-b77998c9-b8bd-434b-a64d-8a9e2e880674.png">

This should help you start -
https://github.com/iiitl/geet-hub-frontend/blob/5d4906aea1a44ac2f6742cb409d911df1e7c0353/src/config/index.json#L6-L20

**Comment by SahilSingh177** [comment]
Please assign this to me.
