### ISSUE TITLE
⚡️ Remove the Call to Action section of the navbar

### ISSUE THREAD

**Issue by PrerakMathur20** [iiitl/geet-hub-frontend#5]
⚡️ Remove the **_Call to Action_** section of the navbar
---

From the navbar, the _**Call to Action**_ button serves no purpose and shouldn't be there.
Remove that Button and remove any code relevant to that Button, without affecting the rest of the project.

<img width="562" alt="Screenshot 2022-09-30 at 4 53 51 AM" src="https://user-images.githubusercontent.com/76054330/193159788-931f9f19-9ff7-43df-ba22-d5c89262e479.png">

This should help you start -
https://github.com/iiitl/geet-hub-frontend/blob/5d4906aea1a44ac2f6742cb409d911df1e7c0353/src/components/Header.tsx#L61-L66

https://github.com/iiitl/geet-hub-frontend/blob/5d4906aea1a44ac2f6742cb409d911df1e7c0353/src/components/Header.tsx#L115-L120

https://github.com/iiitl/geet-hub-frontend/blob/5d4906aea1a44ac2f6742cb409d911df1e7c0353/src/config/index.json#L21-L24

**Comment by Ilikepizza2** [comment]
Hello sir
I'd like to work on this
Can you please assign it to me?

**Comment by palashb01** [comment]
I would like to work on this issue, Please assign it to me

**Comment by PrerakMathur20** [comment]
@palashb01 
To give a fair opportunity to everyone, issues are assigned on one after one basis. As since, you've already been assigned another issue, kindly complete that one, to get another issue assigned.
